
# Site settings
title: Reproducible Research
subtitle: ""
#email: youremailaddress@gmail.com
#description: The Jekyll version of the Massively theme by HTML5 UP.
#baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
baseurl: "/cdcf-workshop2B" # the subpath of your site, e.g. /blog
url: "https://data-curation.github.io/cdcf-workshop2B/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
date_format: "%b %-d, %Y"

sass:
  sass_dir: _sass

social_links:
    twitter: hashtag/CDCF2019
    github: data-curation/cdcf-workshop2B
    rss: rss

include:
  - _pages
  - _posts

exclude:
  - .gitignore
  - LICENSE.txt
  - _site/
  - "*.ai"